env: "dev"
in_memory_storage: false
grpc:
  port: 44044
  timeout: 5s
http:
  address: ":8080"
  timeout: 4s
  idle_timeout: 30s
postgres:
  host: "host.docker.internal"
  port: "5436"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"